[2022-04-03 18:53:14,919] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: workflow1.create_table3 manual__2022-04-03T16:49:55.364228+00:00 [queued]>
[2022-04-03 18:53:14,934] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: workflow1.create_table3 manual__2022-04-03T16:49:55.364228+00:00 [queued]>
[2022-04-03 18:53:14,935] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 18:53:14,935] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-03 18:53:14,935] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 18:53:14,946] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): create_table3> on 2022-04-03 16:49:55.364228+00:00
[2022-04-03 18:53:14,952] {standard_task_runner.py:52} INFO - Started process 63717 to run task
[2022-04-03 18:53:14,958] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'workflow1', 'create_table3', 'manual__2022-04-03T16:49:55.364228+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/extract_file.py', '--cfg-path', '/var/folders/z6/rr0r2zzn64qd2w2102l7_w3r0000gn/T/tmpkztxg94_', '--error-file', '/var/folders/z6/rr0r2zzn64qd2w2102l7_w3r0000gn/T/tmpeficl5mf']
[2022-04-03 18:53:14,960] {standard_task_runner.py:77} INFO - Job 31: Subtask create_table3
[2022-04-03 18:53:19,995] {logging_mixin.py:109} INFO - Running <TaskInstance: workflow1.create_table3 manual__2022-04-03T16:49:55.364228+00:00 [running]> on host Manvis-MacBook-Air.local
[2022-04-03 18:53:25,061] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=workflow1
AIRFLOW_CTX_TASK_ID=create_table3
AIRFLOW_CTX_EXECUTION_DATE=2022-04-03T16:49:55.364228+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-03T16:49:55.364228+00:00
[2022-04-03 18:53:25,066] {base.py:70} INFO - Using connection to: id: postgres_db. Host: 127.0.0.1, Port: 5432, Schema: airflow_db, Login: postgres, Password: ***, extra: {}
[2022-04-03 18:53:25,147] {dbapi.py:225} INFO - Running statement: CREATE TABLE IF NOT EXISTS contracts (id bigint primary key,type varchar(255),energy varchar(255),usage int,usagenet int,createdat date,startdate date,enddate date,filingdatecancellation date,cancellationreason varchar(255),city varchar(255),status varchar(255),productid int, modificationdate date), parameters: None
[2022-04-03 18:53:25,148] {postgres.py:94} INFO - NOTICE:  relation "contracts" already exists, skipping

[2022-04-03 18:53:25,155] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=workflow1, task_id=create_table3, execution_date=20220403T164955, start_date=20220403T165314, end_date=20220403T165325
[2022-04-03 18:53:25,175] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-03 18:53:25,186] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
